/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "dashboard": [],
    "play-vs-ai": [],
    "play-vs-ai.match": [],
    "play-vs-ai.move": [],
    "play-vs-ai.engine-move": [],
    "play-vs-ai.action": [],
    "ai-vs-ai": [],
    "ai-vs-ai.match": [],
    "ai-vs-ai.engine-move": [],
    "ai-vs-ai.action": [],
    "local-match": [],
    "local-match.match": [],
    "local-match.move": [],
    "local-match.action": [],
    "quick-match.queue": [],
    "quick-match.status": [
        {
            "name": "queueKey",
            "required": true
        }
    ],
    "quick-match.cancel": [],
    "quick-match.match": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "quick-match.move": [],
    "quick-match.action": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "user-password.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
